### ISSUE TITLE
Set-up dialog does not work for me

### ISSUE THREAD

**Issue by hypnotoad** [prokosna/sola_mpd#78]
I am new to sola_mpd. I followed the steps in README.md. The service starts up properly with docker/start.sh, the landing page can be opened with my browser.

If I enter my mpd setup and click test, nothing happens (even if I wait a minute). If I enter a wrong setup, I get proper error messages in red what is wrong.

There is no output in the docker console if I enter correct settings (just if I enter wrong ones, there is an error message). In my mpd log, there is nothing printed.

With tcpdump I can see that some tcp connection is established.

There is nothing else that I can see. Is it possible to have some debug messages in sola?

**Comment by prokosna** [comment]
@hypnotoad Do you see any message in the browser console (In Chrome, More tools -> Developer tools -> Console)? 
There should be an error message.

**Comment by prokosna** [comment]
Please also try to directly jump to `http://[your server endpoint]:[port]/home/play_queue`.
I'm not sure but there could be a problem with redirection in your environment.

**Comment by hypnotoad** [comment]
The browser console was a good hint:
```
page-d2e5c30da24b8ecd.js:1 Uncaught (in promise) Error: Invalid argument not valid semver ('0.22.4
' received)
    at o (page-d2e5c30da24b8ecd.js:1:386)
    at c (page-d2e5c30da24b8ecd.js:1:810)
    at page-d2e5c30da24b8ecd.js:1:3106
```

**Comment by prokosna** [comment]
hmm, this is interesting. Your MPD server returns the protocol version string with a new line. Which OS do you use for the MPD server?
I merged the commit to trim the version string. Would you try [updating Sola mpd](https://github.com/prokosna/sola_mpd#how-to-update)?

**Comment by hypnotoad** [comment]
It works now. I have tried two different distributions with mpd here which had this result:
- Debian 11  (0.22.6)
- current hifiberryOs (0.22.11)
I think both lead to the error message above (mentioning a version 0.22.4)

**Comment by prokosna** [comment]
Glad to hear that!
Please feel free to file an issue when you have any other problems/requests.
